// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElBacktop: typeof import('element-plus/es')['ElBacktop']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
export {}
